-- RUN THIS CODE FOR ADDING RELATION

ALTER TABLE borrow ADD FOREIGN KEY (user_code) REFERENCES member(code) ON DELETE CASCADE;
ALTER TABLE borrow ADD FOREIGN KEY (book_code) REFERENCES book(code) ON DELETE CASCADE;