-- RUN THIS CODE FOR ADDING RELATION  (perlu jika pindah database)

ALTER TABLE borrow ADD FOREIGN KEY (member_code) REFERENCES member(code) ON DELETE CASCADE;
ALTER TABLE borrow ADD FOREIGN KEY (book_code) REFERENCES book(code) ON DELETE CASCADE;